# https://terraform-docs.io/user-guide/configuration/

formatter: markdown table

recursive:
  enabled: true
  path: terraform
  include-main: false

sections:
  show:
    - requirements
    - modules
    - providers
    - inputs
    - outputs

# This allows us to customize the injected docs
content: ""

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: name

settings:
  # anchor: true
  color: true
  default: true
  description: true
  # escape: true
  # hide-empty: false
  # html: true
  # indent: 2
  lockfile: false
  # read-comments: true
  required: true
  sensitive: true
  type: true