version: "prometheus/v1"
service: "prometheus"
labels:
  team: observability
slos:
  - name: "query-latency"
    objective: 99
    description: "99% of PromQL queries complete within 10 seconds"
    sli:
      events:
        error_query: |
          sum(increase(prometheus_engine_query_duration_histogram_seconds_count{
            slice="inner_eval"
          }[{{.window}}]))
          -
          sum(increase(prometheus_engine_query_duration_histogram_seconds_bucket{
            slice="inner_eval",
            le="10"
          }[{{.window}}]))
        total_query: |
          sum(increase(prometheus_engine_query_duration_histogram_seconds_count{
            slice="inner_eval"
          }[{{.window}}]))
    alerting:
      name: PrometheusQueryLatencyBudgetBurn
      labels:
        severity: warning
      annotations:
        summary: "Prometheus query latency SLO error budget burn rate is high"
