version: "prometheus/v1"
service: "prometheus"
labels:
  team: observability
slos:
  - name: "storage"
    objective: 100
    description: "No WAL corruptions occur"
    sli:
      events:
        error_query: |
          sum(increase(prometheus_tsdb_wal_corruptions_total[{{.window}}]))
        total_query: |
          sum(increase(prometheus_tsdb_wal_corruptions_total[{{.window}}])) + 1
    alerting:
      name: PrometheusStorageBudgetBurn
      labels:
        severity: critical
      annotations:
        summary: "Prometheus storage SLO error budget burn rate is high"
