name: Test the Terraform product module

on:
  workflow_dispatch:
  workflow_call:

jobs:
  setup-microceph:
    name: Install and setup Microceph
    uses: canonical/observability-stack/.github/workflows/_setup_microceph.yml@feat/cos-upgrade # TODO: Fix branch
  terraform-test:
    name: Test product module
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        product: [ "cos_lite" ]
        scenario: [ "tls_full", "tls_external", "tls_internal", "tls_none" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install concierge --classic
          sudo concierge prepare --juju-channel 3.6/stable -p microk8s --extra-snaps just,astral-uv,terraform
      - name: Test deployment
        run: |
          export S3_ENDPOINT=http://$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc'):8080
          export S3_ACCESS_KEY=access-key
          export S3_SECRET_KEY=secret-key
          just integration ${{ matrix.product }}/${{ matrix.scenario }}/test_upgrade_${{ matrix.product }}_${{ matrix.scenario }}.py
