name: Test the Terraform product module

on:
  workflow_dispatch:
  workflow_call:

jobs:
  terraform-test:
    name: Test the Terraform product module
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        product: [ "cos_lite" ]
        scenario: [ "tls_full", "tls_external", "tls_internal", "tls_none" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install concierge --classic
          sudo concierge prepare -p microk8s --extra-snaps just,astral-uv,terraform
      - name: Test deployment
        run: |
          just integration ${{ matrix.product }}/${{ matrix.scenario }}/test_upgrade_${{ matrix.scenario }}.py
