name: Terraform

on:
  workflow_call:

jobs:
  microceph:
    name: microceph
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and configure microceph
        run: |
          # https://github.com/canonical/microceph-action/blob/main/microceph.sh
          function check_ceph_ok_or_exit () {
              i=0
              for i in {1..5}; do
                  if sudo microceph.ceph status | grep HEALTH_OK; then
                      break
                  else
                      sudo microceph.ceph status
                      sleep 30
                      sudo microceph.ceph health detail
                  fi
              done
              if [ "$i" -eq 5 ]; then
                  exit 1
              fi
          }

          sudo snap install microceph
          sudo microceph cluster bootstrap
          sleep 30s
          sudo microceph.ceph config set "mon.$(hostname)" mon_data_avail_warn 6
          sudo microceph disk add loop,2G,3
          check_ceph_ok_or_exit

          sudo microceph enable rgw --port 8080 --ssl-port 8443
          sudo microceph.radosgw-admin user create --uid=user --display-name=User
          sudo microceph.radosgw-admin key create --uid=user --key-type=s3 --access-key=access-key --secret-key=secret-key
