name: Markdown style checks

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
    - '*'
    paths:
    - 'docs/**'   # Only run on changes to the docs directory

jobs:
  markdown-lint:
    name: Markdown lint
    uses: canonical/sphinx-stack/.github/workflows/markdown-style-checks.yml@2.0
