name: Release Terraform modules

on:
  workflow_dispatch: {}
  push:
    branches:
      - track/**

permissions:
  # Required for all workflows
  security-events: write
  # Only required for workflows in private repositories
  actions: read
  # Write permission needed for the reusable workflow to push git tags
  contents: write

jobs:
  release-terraform:
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag-prefix: tf-cos-
            path: terraform/cos
          - tag-prefix: tf-cos-lite-
            path: terraform/cos-lite
    uses: canonical/observability/.github/workflows/terraform-release.yaml@v2
    secrets: inherit
    with:
      terraform-tag-prefix: ${{ matrix.tag-prefix }}
      terraform-path: ${{ matrix.path }}
