name: Terraform

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.tf"
      - "tests/integration/**"

jobs:
  changes:
    name: Detect changed products
    runs-on: ubuntu-latest
    outputs:
      cos: ${{ steps.filter.outputs.cos }}
      cos_lite: ${{ steps.filter.outputs.cos_lite }}
      cos_dev: ${{ steps.filter.outputs.cos_dev }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter changed paths per product
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            # Shared paths affect *multiple* products, so they trigger as well
            shared: &shared
              - '.github/workflows/terraform.yml'
              - '.github/workflows/_integration.yml'
              - 'tests/integration/conftest.py'
              - 'tests/integration/helpers.py'
            cos:
              - *shared
              - 'terraform/cos/**'
              - 'tests/integration/cos/**'
            cos_lite:
              - *shared
              - 'terraform/cos-lite/**'
              - 'tests/integration/cos_lite/**'
            cos_dev:
              - *shared
              - 'terraform/cos-dev/**'
              - 'tests/integration/cos_dev/**'
  test-integration-cos:
    name: COS Terraform integration

    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.cos == 'true' }}
    uses: canonical/observability-stack/.github/workflows/_integration.yml@feat/ceph-charm
    with:
      product: cos
      runner: self-hosted-linux-amd64-noble-xlarge