name: Terraform

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.tf"
      - "tests/integration/**"

jobs:
  test-integration-cos:
    name: COS Terraform integration

    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.cos == 'true' }}
    uses: canonical/observability-stack/.github/workflows/_integration.yml@feat/ceph-charm
    with:
      product: cos
      runner: self-hosted-linux-amd64-noble-xlarge